### ISSUE TITLE
Terminology, OGC vs ArcGIS RESTful services

### ISSUE THREAD

**Issue by emiliom** [cheginit/pygeoogc#1]
I wanted to point out what I see as an inconsistency in terminology and references.

OGC, the Open Geospatial Consortium, has developed many open, community standards. Two of the oldest and most common ones are WMS and WFS. 

ESRI ArcGIS RESTful services (officially the "ArcGIS REST API", I think), while widely used b/c the ESRI platform is widespread, are not an OGC standard. So, having these services in a package that has ogc is confusing, I think. It gets more confusing b/c ArcGIS RESTful services implements its own web map services that ESRI also calls WMS, but it's not OGC WMS. 

To avoid ambiguity, OGC standards should be referred to as, say, ogcwms and ogcwfs. I think it'd be better to split your WMS (and WFS) class into OGCWMS vs, say, AGRWMS. You may consider also renaming the package itself to something more generic so it doesn't imply OGC services only; for example, pygeoaccess. But I realize that's a lot more work for you at this stage!

Anyway, just my 2 cents. You've created a set of fantastic packages!

**Comment by cheginit** [comment]
Yes, I totally agree. `WMS` and `WFS` classes are general and can be used for both ESRI- and OGC-based services. RESTful-based services, however, can vary and as far as I know, we can't have a general function.

I like `PyGeoAccess` name. I will into renaming it.

**Comment by emiliom** [comment]
> Yes, I totally agree. WMS and WFS classes are general and can be used for both ESRI- and OGC-based services. 

Well, the ESRI and OGC based services may share names and general capabilities (I'm not very familiar with the ESRI services), but I suspect they differ in important ways. Personally, I'm not convinced the benefits of having these common classes outweigh the potential confusion to users who are looking for a simpler and more convenient way to access data from well known geospatial web service types -- OGC & ESRI.

> RESTful-based services, however, can vary and as far as I know, we can't have a general function.

Absolutely. But I wonder if the wide variety of services you're currently including in `ServiceURL().restful` adhere to the more common definitions of a "RESTful" service. Looser definitions of it often encompass key-value HTTP GET requests like OGC WFS and OGC WMS.

I guess this all boils down to me getting confused about where you want to go with your packages, specially `pygeoogc` (the scope of `pynhd` is very distinctive and meets a unique niche in the Python ecosystem, in my opinion!). But don't worry about my confusion! :wink: They are **your** packages. I'm just trying to provide hopefully useful feedback. At the same time, I would encourage you to work more actively with existing community packages like `OWSLib`, contributing directly to them whenever possible.

**Comment by cheginit** [comment]
> Well, the ESRI and OGC based services may share names and general capabilities (I'm not very familiar with the ESRI services), but I suspect they differ in important ways.
> I guess this all boils down to me getting confused about where you want to go with your packages, specially pygeoogc.

I have tested the function with both GeoServer- and ESRI-based services and so far haven't faced any issue. `OWSLib` takes care of the validation step for the most part but it's not very stable when it comes to sending requests. I tried to tailor `PyGeoOGC` for GeoServer- and ESRI-based services. At the moment, my plan is to continue and add support for web services that I use for my own projects as well as reasonable features that users ask for. I am hoping that as more users, like yourself, rely on Hydrodata packages they will help to shape a roadmap for future development.

> Personally, I'm not convinced the benefits of having these common classes outweigh the potential confusion to users who are looking for a simpler and more convenient way to access data from well known geospatial web service types -- OGC & ESRI.
> I wonder if the wide variety of services you're currently including in `ServiceURL().restful` adhere to the more common definitions of a "RESTful" service.

One of the reasons that I have added `ServiceURL` is to showcase the types of services that this package support. My plan is to update this class regularly as users, including myself, test these classes for various web services, and get the expected results. I am planning to create a JSON file for these URLs (which will be read by `ServiceURL`) so users can add the classes more easily. At the end of the day, the main purpose is to provide a unified interface to various web services and utilities to work with the returned responses.

> But don't worry about my confusion! wink They are your packages. I'm just trying to provide hopefully useful feedback.

I appreciate this helpful feedback and counting on them for future developments.

> At the same time, I would encourage you to work more actively with existing community packages like OWSLib, contributing directly to them whenever possible.

Absolutely, that's the beauty of open-source projects, we can fly much higher as a flock!

**Comment by cheginit** [comment]
I forgot to include this issue in the related commit message but I modified the package based on some of the things that we discussed in [this](https://github.com/cheginit/pygeoogc/commit/fcfede50cb88aa8397ac04da9e087175989f4390) commit.

**Comment by cheginit** [comment]
I am going to close this for now, please feel free to open up if you wanted to discuss it more.
