### ISSUE TITLE
WMS service error

### ISSUE THREAD

**Issue by DavidChoi76** [cheginit/pygeoogc#2]
I'm not good at GIS web service and coordinate system. So I don't know what the exact problem is.

I got an error in the third cell in the `3dep` notebook.
dem = py3dep.get_map("DEM", geometry, resolution=30, geo_crs="epsg:4326", crs="epsg:3857").
The error is from the WMS server. Do you know how to solve the problem?

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-3-f52642f97686> in <module>
----> 1 dem = py3dep.get_map("DEM", geometry, resolution=30, geo_crs="epsg:4326", crs="epsg:3857")
      2 dem.name = "dem"
      3 dem.attrs["units"] = "meters"
      4 slope = py3dep.get_map("Slope Degrees", geometry, resolution=30)
      5 slope = py3dep.deg2mpm(slope)

/srv/conda/envs/notebook/lib/python3.8/site-packages/py3dep/py3dep.py in get_map(layers, geometry, resolution, geo_crs, crs, fill_holes)
     76     _layers = [f"3DEPElevation:{lyr}" for lyr in _layers]
     77 
---> 78     wms = WMS(ServiceURL().wms.nm_3dep, layers=_layers, outformat="image/tiff", crs=crs)
     79     r_dict = wms.getmap_bybox(_geometry.bounds, resolution, box_crs=crs)
     80 

/srv/conda/envs/notebook/lib/python3.8/site-packages/pygeoogc/pygeoogc.py in __init__(self, url, layers, outformat, version, crs, validation)
    456         self.layers = [self.layers] if isinstance(self.layers, str) else self.layers
    457         if validation:
--> 458             self.validate_wms()
    459 
    460     def getmap_bybox(

/srv/conda/envs/notebook/lib/python3.8/site-packages/pygeoogc/pygeoogc.py in validate_wms(self)
    390     def validate_wms(self) -> None:
    391         """Validate input arguments with the WMS service."""
--> 392         wms = WebMapService(self.url, version=self.version)
    393 
    394         valid_layers = {wms[lyr].name: wms[lyr].title for lyr in list(wms.contents)}

/srv/conda/envs/notebook/lib/python3.8/site-packages/owslib/wms.py in WebMapService(url, version, xml, username, password, parse_remote_metadata, timeout, headers, auth)
     52             timeout=timeout, headers=headers, auth=auth)
     53     elif version in ['1.3.0']:
---> 54         return wms130.WebMapService_1_3_0(
     55             clean_url, version=version, xml=xml, parse_remote_metadata=parse_remote_metadata,
     56             timeout=timeout, headers=headers, auth=auth)

/srv/conda/envs/notebook/lib/python3.8/site-packages/owslib/map/wms130.py in __init__(self, url, version, xml, username, password, parse_remote_metadata, timeout, headers, auth)
     73             self._capabilities = reader.readString(xml)
     74         else:  # read from server
---> 75             self._capabilities = reader.read(self.url, timeout=self.timeout)
     76 
     77         self.request = reader.request

/srv/conda/envs/notebook/lib/python3.8/site-packages/owslib/map/common.py in read(self, service_url, timeout)
     63         # now split it up again to use the generic openURL function...
     64         spliturl = self.request.split('?')
---> 65         u = openURL(spliturl[0], spliturl[1], method='Get',
     66                     timeout=timeout, headers=self.headers, auth=self.auth)
     67 

/srv/conda/envs/notebook/lib/python3.8/site-packages/owslib/util.py in openURL(url_base, data, method, cookies, username, password, timeout, headers, verify, cert, auth)
    207 
    208     if req.status_code in [404, 500, 502, 503, 504]:    # add more if needed
--> 209         req.raise_for_status()
    210 
    211     # check for service exceptions without the http header set

/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 502 Server Error: Bad Gateway for url: https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0

**Comment by cheginit** [comment]
Thanks for the report. As the error message states it's a 500 error which means that the service is not available. Unfortunately, 3DEP WMS service has been unstable over the past couple of days. I reported the issue to the people who maintain the National Map web services and they told me they're working on a fix. So, please check again later. I will update you as soon as I hear any news from them.

**Comment by cheginit** [comment]
The 3DEP service is back online, please give it a try and let me know if it works.

**Comment by cheginit** [comment]
The issue resolved. Please feel free to re-open if you still have an issue using it.
