### ISSUE TITLE
README refers to file that does not exist in repo

### ISSUE THREAD

**Issue by jacklinke** [cheginit/pygeoogc#52]
The readme refers to [urls.yml](https://github.com/cheginit/pygeoogc/blob/main/pygeoogc/static/urls.yml) within the `static` folder, but that folder and file do not seem to exist or have not yet been committed to the repo.

[Release 0.2.0](https://github.com/cheginit/pygeoogc/blob/c2207bd08bb81b021a8064407a4440761a08c4f0/HISTORY.rst#020-2020-12-06) notes...

> Moved all the web services URLs to a YAML file that ServiceURL class reads. It makes managing the new URLs easier. The file is located at pygeoogc/static/urls.yml.

But the file seems to have been missed somehow.

**Comment by cheginit** [comment]
Thanks for catching this. I changed this in favor of a more secure and performant way of representing the URLs. You can check out the changelong [here](https://github.com/cheginit/pygeoogc/blob/c2207bd08bb81b021a8064407a4440761a08c4f0/HISTORY.rst#internal-changes).

I forgot to change the readme to reflect that. I will fix it.

Now, you can find the URLs [here](https://github.com/cheginit/pygeoogc/blob/c2207bd08bb81b021a8064407a4440761a08c4f0/pygeoogc/pygeoogc.py#L691-L756) or by just simply instantiating the `ServiceURL` class.

```python
from pygeoogc import ServiceURL

print(ServiceURL())
```
